# Generated by Django 3.1.4 on 2020-12-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservices',
            name='address',
            field=models.CharField(default='ISL', max_length=200),
        ),
        migrations.AddField(
            model_name='clientservices',
            name='email',
            field=models.EmailField(default='@gmail.com', max_length=254),
        ),
    ]
