# Generated by Django 3.1.4 on 2020-12-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0002_auto_20201231_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='company',
            field=models.CharField(default='Jazz/Mobilink', max_length=50),
        ),
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.EmailField(default='@mobilink.com', max_length=254),
        ),
        migrations.AddField(
            model_name='clientservices',
            name='invoices',
            field=models.CharField(default='invoice000', max_length=100),
        ),
    ]
