# Generated by Django 3.1.4 on 2020-12-31 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0003_auto_20201231_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientservices',
            name='invoices',
        ),
    ]
