# Generated by Django 3.1.4 on 2021-01-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0004_remove_clientservices_invoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxauthority', models.CharField(max_length=200)),
                ('taxrate', models.FloatField()),
            ],
            options={
                'db_table': 'TaxAuthority',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ntn', models.IntegerField()),
                ('pstn', models.IntegerField()),
                ('address', models.CharField(max_length=254)),
                ('logo', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Vendors',
            },
        ),
    ]
