# Generated by Django 3.1.4 on 2021-01-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0005_taxauthority_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='pstn',
        ),
        migrations.AddField(
            model_name='vendor',
            name='salestax',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='taxauthority',
            name='taxauthority',
            field=models.CharField(default='punjab/sindh', max_length=200),
        ),
        migrations.AlterField(
            model_name='taxauthority',
            name='taxrate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(default='LHR', max_length=254),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(default='ccc', max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ntn',
            field=models.IntegerField(default=0),
        ),
    ]
