# Generated by Django 3.1.4 on 2021-01-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0006_auto_20210103_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='salestax',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
