# Generated by Django 3.1.4 on 2021-01-13 07:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0007_auto_20210104_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='--', max_length=500)),
                ('fishbowlid', models.CharField(max_length=20)),
                ('vendorInvoiceId', models.CharField(max_length=20)),
                ('submissionToClientDate', models.DateField(default=datetime.date(2021, 1, 13))),
                ('advancepayment', models.FloatField(default=30.0)),
                ('discountOffered', models.FloatField(default=0)),
                ('subtotal', models.FloatField(default=0.0)),
                ('clientservices', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientservices', to='KHSystemApp.clientservices')),
                ('taxauthority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxauthories', to='KHSystemApp.taxauthority')),
                ('vendors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='KHSystemApp.vendor')),
            ],
        ),
    ]
