# Generated by Django 3.1.4 on 2021-01-13 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0008_invoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='submissionToClientDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
