# Generated by Django 3.1.4 on 2021-01-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0009_auto_20210113_1256'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoices',
            table='Invoices',
        ),
    ]
