# Generated by Django 3.1.4 on 2021-01-13 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0010_auto_20210113_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='KHSystemApp.clients'),
        ),
    ]
