# Generated by Django 3.1.4 on 2021-01-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0011_invoices_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='subtotal',
        ),
    ]
