# Generated by Django 3.1.4 on 2021-01-20 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0012_remove_invoices_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('estimateGenerationDate', models.DateField(default=django.utils.timezone.now)),
                ('SharedToClientDate', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(default='Email', max_length=250)),
                ('description', models.TextField()),
                ('quantity', models.TextField()),
                ('rate', models.TextField()),
                ('amount', models.TextField()),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='KHSystemApp.invoices')),
            ],
            options={
                'db_table': 'Estimate',
            },
        ),
        migrations.AlterField(
            model_name='invoices',
            name='title',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
