# Generated by Django 3.1.4 on 2021-01-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0013_auto_20210120_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimate',
            old_name='SharedToClientDate',
            new_name='sharedToClientDate',
        ),
    ]
