# Generated by Django 3.1.4 on 2021-01-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0014_auto_20210125_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='quantity',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='rate',
            field=models.TextField(blank=True),
        ),
    ]
