# Generated by Django 3.1.4 on 2021-01-27 17:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0015_auto_20210125_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='KHSystemApp.invoices')),
                ('quotationReceivedDate', models.DateField(default=django.utils.timezone.now)),
                ('quotationFile', models.FileField(upload_to='documents/')),
            ],
            options={
                'db_table': 'Quotation',
            },
        ),
    ]
