# Generated by Django 3.1.4 on 2021-01-28 17:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0016_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='KHSystemApp.invoices')),
                ('poRequestedDate', models.DateField(default=django.utils.timezone.now)),
                ('poReceivedDate', models.DateField(blank=True)),
                ('poFile', models.FileField(blank=True, upload_to='documents/')),
            ],
            options={
                'db_table': 'PurchaseOrder',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequsition',
            fields=[
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='KHSystemApp.invoices')),
                ('prRequestedDate', models.DateField(default=django.utils.timezone.now)),
                ('prReceivedDate', models.DateField(blank=True)),
                ('prNumber', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'PurchaseRequsition',
            },
        ),
    ]
