# Generated by Django 3.1.4 on 2021-01-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0017_purchaseorder_purchaserequsition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequsition',
            name='prNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
