# Generated by Django 3.1.4 on 2021-01-30 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0018_auto_20210128_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='KHSystemApp.invoices')),
                ('reInvNumber', models.CharField(blank=True, max_length=20)),
                ('reInvDate', models.DateField(blank=True)),
            ],
            options={
                'db_table': 'Reimbursement',
            },
        ),
    ]
