# Generated by Django 3.1.4 on 2021-01-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0019_reimbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='poNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
