# Generated by Django 3.1.4 on 2021-01-31 02:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0020_purchaseorder_ponumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pti',
            fields=[
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='KHSystemApp.invoices')),
                ('ptiDate', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'PermissionToInvoice',
            },
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='poReceivedDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchaserequsition',
            name='prReceivedDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='reInvDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
