# Generated by Django 3.1.4 on 2021-02-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0021_auto_20210131_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='pti',
            name='deduction',
            field=models.IntegerField(default=0.0),
        ),
    ]
