# Generated by Django 3.1.4 on 2021-02-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0022_pti_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='estimateFormat',
            field=models.CharField(default='Line Numbering', max_length=25),
        ),
    ]
