# Generated by Django 3.1.4 on 2021-02-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0023_estimate_estimateformat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimateFormat',
            field=models.CharField(choices=[('Line Numbering', 'Line Numbering'), ('Header Numbering', 'Header Numbering')], max_length=25),
        ),
    ]
