# Generated by Django 3.1.4 on 2021-02-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0024_auto_20210214_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimateFormat',
            field=models.CharField(choices=[('LN', 'Line Numbering'), ('HN', 'Header Numbering')], max_length=25),
        ),
    ]
