# Generated by Django 3.1.4 on 2021-02-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0025_auto_20210216_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pti',
            name='deduction',
        ),
    ]
