# Generated by Django 3.1.4 on 2021-02-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0026_remove_pti_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pti',
            name='deduction',
            field=models.CharField(default='Nil', max_length=20),
        ),
    ]
