# Generated by Django 3.1.4 on 2021-02-27 17:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0027_pti_deduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='iPortalPreparation',
            fields=[
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='KHSystemApp.invoices')),
                ('uploadedDate', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('emailText', models.TextField()),
            ],
            options={
                'db_table': 'iPortalPreparation',
            },
        ),
        migrations.CreateModel(
            name='JazzReceiptNoRequest',
            fields=[
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='KHSystemApp.invoices')),
                ('receiptReqDate', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'JazzReceiptNumberRequest',
            },
        ),
        migrations.CreateModel(
            name='ReceiptNumberReceived',
            fields=[
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='KHSystemApp.invoices')),
                ('receiptReceivedDate', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('receiptNumber', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ReceiptNumber',
            },
        ),
        migrations.CreateModel(
            name='SalesTaxInvoice',
            fields=[
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='KHSystemApp.invoices')),
                ('salesTaxInvoiceRequestedDate', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('salesTaxInvoiceReceivedDate', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('salesTaxFile', models.FileField(blank=True, upload_to='documents/')),
            ],
            options={
                'db_table': 'SalesTaxInvoice',
            },
        ),
    ]
