# Generated by Django 3.1.4 on 2021-02-28 17:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0028_iportalpreparation_jazzreceiptnorequest_receiptnumberreceived_salestaxinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountHeadEntranceDate', models.DateField(default=django.utils.timezone.now)),
                ('accountHeadTitle', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'AccountHead',
            },
        ),
        migrations.CreateModel(
            name='PettyCashEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pettyCashDate', models.DateField(default=django.utils.timezone.now)),
                ('narration', models.CharField(max_length=250)),
                ('branch', models.CharField(default='ISB', max_length=20)),
                ('debt', models.FloatField(default=0.0)),
                ('credit', models.FloatField(default=0.0)),
                ('accountHead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountHeads', to='KHSystemApp.accounthead')),
            ],
            options={
                'db_table': 'PettyCashEntry',
            },
        ),
    ]
