# Generated by Django 3.1.4 on 2021-03-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0029_accounthead_pettycashentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='notes',
            field=models.TextField(blank=True, default='Nil'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='notes',
            field=models.TextField(blank=True, default='Nil'),
        ),
        migrations.AddField(
            model_name='iportalpreparation',
            name='notes',
            field=models.TextField(blank=True, default='Nil'),
        ),
        migrations.AddField(
            model_name='jazzreceiptnorequest',
            name='notes',
            field=models.TextField(blank=True, default='Nil'),
        ),
        migrations.AddField(
            model_name='pti',
            name='notes',
            field=models.TextField(blank=True, default='Nil'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, default='Nil'),
        ),
        migrations.AddField(
            model_name='purchaserequsition',
            name='notes',
            field=models.TextField(blank=True, default='Nil'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='notes',
            field=models.TextField(blank=True, default='Nil'),
        ),
        migrations.AddField(
            model_name='receiptnumberreceived',
            name='notes',
            field=models.TextField(blank=True, default='Nil'),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='notes',
            field=models.TextField(blank=True, default='Nil'),
        ),
        migrations.AddField(
            model_name='salestaxinvoice',
            name='notes',
            field=models.TextField(blank=True, default='Nil'),
        ),
    ]
