# Generated by Django 3.1.4 on 2021-03-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0030_auto_20210306_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='notes',
            field=models.CharField(blank=True, default='Nil', max_length=300),
        ),
    ]
