# Generated by Django 3.1.4 on 2021-03-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0031_auto_20210306_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='estimate_bytes_pdf',
            field=models.BinaryField(blank=True),
        ),
    ]
