# Generated by Django 3.1.4 on 2021-03-09 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0032_estimate_estimate_bytes_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssembleExportEmail',
            fields=[
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='KHSystemApp.invoices')),
                ('emailText', models.TextField()),
            ],
            options={
                'db_table': 'AssembleEmailText',
            },
        ),
    ]
