# Generated by Django 3.1.4 on 2021-03-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0033_assembleexportemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxauthority',
            name='isReimbursed',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'No')], default=False),
        ),
    ]
