# Generated by Django 3.1.4 on 2021-03-11 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0034_taxauthority_isreimbursed'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstimateTypeTitle', models.TextField(max_length=300)),
                ('isTaxable', models.BooleanField(choices=[(True, 'YES'), (False, 'No')], default=True)),
            ],
            options={
                'db_table': 'EstimateType',
            },
        ),
        migrations.AddField(
            model_name='estimate',
            name='estimateType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estTypes', to='KHSystemApp.estimatetype'),
        ),
    ]
