# Generated by Django 3.1.4 on 2021-03-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0035_auto_20210311_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatetype',
            name='EstimateTypeTitle',
            field=models.CharField(max_length=300),
        ),
    ]
