# Generated by Django 3.1.4 on 2021-03-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0036_auto_20210314_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='jazzreceiptnorequest',
            name='advRiFile',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='jazzreceiptnorequest',
            name='initialPtiFile',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
