# Generated by Django 3.1.4 on 2021-03-21 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0037_auto_20210320_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptNoRequestUploads',
            fields=[
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='KHSystemApp.invoices')),
                ('initialPtiFile', models.FileField(blank=True, upload_to='documents/')),
                ('advRiFile', models.FileField(blank=True, upload_to='documents/')),
            ],
            options={
                'db_table': 'JazzReceiptRequestUploads',
            },
        ),
        migrations.RemoveField(
            model_name='jazzreceiptnorequest',
            name='advRiFile',
        ),
        migrations.RemoveField(
            model_name='jazzreceiptnorequest',
            name='initialPtiFile',
        ),
    ]
