# Generated by Django 3.1.4 on 2021-03-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0039_auto_20210321_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembleexportemail',
            name='emailsPdfFile',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
