# Generated by Django 3.1.4 on 2021-03-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0040_assembleexportemail_emailspdffile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iportalpreparation',
            name='emailText',
        ),
        migrations.AddField(
            model_name='iportalpreparation',
            name='ptiPdfFile',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='iportalpreparation',
            name='riPdfFile',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
