# Generated by Django 3.1.4 on 2021-03-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0041_auto_20210322_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembleexportemail',
            name='emailsPdfFile',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
