# Generated by Django 3.1.4 on 2021-03-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHSystemApp', '0042_auto_20210324_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxauthority',
            name='taxauthority',
            field=models.CharField(default='PST/SST', max_length=200),
        ),
    ]
